# Generated by Django 4.1.7 on 2023-02-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Choreographer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                (
                    "pronouns",
                    models.CharField(
                        choices=[
                            ("he/him/his", "he/him/his"),
                            ("she/her/hers", "she/her/hers"),
                            ("they/them/theirs", "they/them/theirs"),
                        ],
                        max_length=30,
                    ),
                ),
                ("based_in", models.CharField(max_length=30)),
                ("intro", models.TextField()),
                ("instagram_handle", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Choreography",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("choreographer", models.CharField(max_length=30)),
                ("music_title", models.CharField(max_length=100)),
                ("music_artist", models.CharField(max_length=30)),
                (
                    "style",
                    models.CharField(
                        choices=[
                            ("hip-hop", "Hip-Hop"),
                            ("locking", "Locking"),
                            ("popping", "Popping"),
                            ("house", "House"),
                            ("breaking", "Breaking"),
                            ("jazz", "Jazz"),
                            ("afro", "Afro"),
                            ("dancehall", "Dancehall"),
                            ("heels", "Heels"),
                            ("comtemporary", "Comtemporary"),
                        ],
                        max_length=30,
                    ),
                ),
                ("video_url", models.URLField()),
            ],
            options={"ordering": ["created"],},
        ),
    ]
