# Generated by Django 4.1.7 on 2023-02-21 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Choreography",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("choreographer", models.CharField(max_length=30)),
                ("music_title", models.CharField(max_length=100)),
                (
                    "style",
                    models.CharField(
                        choices=[
                            ("hip-hop", "Hip-Hop"),
                            ("locking", "Locking"),
                            ("popping", "Popping"),
                            ("house", "House"),
                            ("breaking", "Breaking"),
                            ("jazz", "Jazz"),
                            ("afro", "Afro"),
                            ("dancehall", "Dancehall"),
                            ("heels", "Heels"),
                            ("comtemporary", "Comtemporary"),
                        ],
                        max_length=30,
                    ),
                ),
                ("video_url", models.URLField()),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choreographies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["created"],},
        ),
    ]
