# Generated by Django 4.1.7 on 2023-02-21 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("choreos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choreography",
            name="style",
            field=models.CharField(
                choices=[
                    ("hip-hop", "Hip-Hop"),
                    ("locking", "Locking"),
                    ("popping", "Popping"),
                    ("house", "House"),
                    ("breaking", "Breaking"),
                    ("jazz", "Jazz"),
                    ("afro", "Afro"),
                    ("dancehall", "Dancehall"),
                    ("heels", "Heels"),
                    ("contemporary", "Contemporary"),
                ],
                max_length=30,
            ),
        ),
    ]
