# Generated by Django 4.1.7 on 2023-02-17 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("choreos", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Choreographer",),
        migrations.RemoveField(model_name="choreography", name="music_artist",),
    ]
