# Generated by Django 3.1.14 on 2023-02-22 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choreos', '0003_alter_choreography_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choreography',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='choreography',
            name='style',
            field=models.CharField(choices=[('hip-hop', 'Hip-Hop'), ('locking', 'Locking'), ('popping', 'Popping'), ('house', 'House'), ('breaking', 'Breaking'), ('jazz', 'Jazz'), ('afro', 'Afro'), ('dancehall', 'Dancehall'), ('heels', 'Heels'), ('contemporary', 'Contemporary'), ('k-pop', 'K-Pop')], max_length=30),
        ),
    ]
